# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: newsfeed.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0enewsfeed.proto\x12\x04news\"\x1f\n\x0bNewsRequest\x12\x10\n\x08news_url\x18\x01 \x01(\t\"\x1f\n\x0cNewsResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2C\n\x0bNewsService\x12\x34\n\x0bSendNewsURL\x12\x11.news.NewsRequest\x1a\x12.news.NewsResponseb\x06proto3')



_NEWSREQUEST = DESCRIPTOR.message_types_by_name['NewsRequest']
_NEWSRESPONSE = DESCRIPTOR.message_types_by_name['NewsResponse']
NewsRequest = _reflection.GeneratedProtocolMessageType('NewsRequest', (_message.Message,), {
  'DESCRIPTOR' : _NEWSREQUEST,
  '__module__' : 'newsfeed_pb2'
  # @@protoc_insertion_point(class_scope:news.NewsRequest)
  })
_sym_db.RegisterMessage(NewsRequest)

NewsResponse = _reflection.GeneratedProtocolMessageType('NewsResponse', (_message.Message,), {
  'DESCRIPTOR' : _NEWSRESPONSE,
  '__module__' : 'newsfeed_pb2'
  # @@protoc_insertion_point(class_scope:news.NewsResponse)
  })
_sym_db.RegisterMessage(NewsResponse)

_NEWSSERVICE = DESCRIPTOR.services_by_name['NewsService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NEWSREQUEST._serialized_start=24
  _NEWSREQUEST._serialized_end=55
  _NEWSRESPONSE._serialized_start=57
  _NEWSRESPONSE._serialized_end=88
  _NEWSSERVICE._serialized_start=90
  _NEWSSERVICE._serialized_end=157
# @@protoc_insertion_point(module_scope)
